# Generated by Django 5.0.1 on 2024-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='blog_user_role',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
