# Generated by Django 5.0.1 on 2024-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_bloguser_blog_user_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_created_by', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_description', models.TextField()),
                ('blog_is_active', models.CharField(default='normal', max_length=50)),
                ('blog_published_date', models.DateTimeField(auto_now_add=True)),
                ('blog_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
