# Generated by Django 5.0.1 on 2024-02-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_blogposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPosts',
            new_name='BlogPost',
        ),
    ]
