# Generated by Django 5.0.1 on 2024-02-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_rename_blogposts_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.bloguser'),
        ),
    ]
